//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Nullable<long> UserID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public long CartID { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
